<a href="https://www.kaggle.com/code/alinahurtova/practice-1-nn?scriptVersionId=352466036" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

Імпорт модулів

In [4]:
import torch

# Завдання 1

Перегляньте інформацію про доступні процесори, та виведіть про них інформацію

In [5]:
print(torch.cuda.is_available())  # True/False

if torch.cuda.is_available():
    print(torch.cuda.device_count())  # Кількість GPU
    print(torch.cuda.get_device_name(0))  # Назва першого GPU

tensor = torch.tensor([1, 2, 3])
print(tensor.device)  # CPU

True
2
Tesla T4
cpu


# Завдання 2
Підключіться до процесора GPU, та знову виведіть інформацію про доступні процесори

In [6]:
tensor_gpu = tensor.to("cuda")

tensor_gpu

tensor([1, 2, 3], device='cuda:0')

# Завдання 3
Створіть випадковий тензор розміру (2, 3). Виведіть інформацію про його:

* розмір
* тип даних
* процесор
* наявність градієнта

In [7]:
tensor = torch.randn(2,3)

In [8]:
tensor

tensor([[-0.1288,  0.8195,  1.0566],
        [ 1.0294, -0.0931,  0.5389]])

In [9]:
tensor.dtype

torch.float32

In [28]:
tensor.shape

torch.Size([2, 3])

In [29]:
tensor.device

device(type='cpu')

# Завдання 4

Створіть 2 тензора розміру 100. Виведіть
* суму векторів
* частку векторів(перед цим замініть один елемент на 0)
* максимальне та мінімальне значення(методи .min() .max())
* середнє значення(метод .mean())
* квадрад різниці
* середнє значення квадрату різниці

In [30]:
tensor1=torch.randn(100)
tensor2=torch.randn(100)

In [31]:
tensor1

tensor([ 1.2581,  0.7955, -1.4139,  0.1449,  0.0132,  0.6344,  0.1111, -1.5653,
         0.3191,  0.2518, -1.7122,  0.8712,  0.1205, -0.8535,  1.0637,  0.6382,
         0.6466, -0.3319,  0.0754, -1.7838, -0.5912, -1.4135, -0.8303, -1.2087,
        -0.6081, -0.3021,  0.5997,  0.5238, -1.1171,  0.4343, -0.4236, -0.5454,
        -0.2310, -0.6695,  0.2076, -0.7029, -0.3145,  0.0603, -0.1453,  0.8540,
        -1.7766,  0.3939,  2.0611,  1.1621, -1.2707, -1.4596,  0.6406,  0.1036,
         0.8782, -0.6963, -0.6683, -1.0389,  0.2715,  1.3795,  0.8436,  0.2562,
         0.4246,  0.4381, -2.1380,  0.0456,  0.0290, -1.5595,  0.7121, -2.8059,
         0.8233,  0.8985, -0.5783, -1.2779, -0.7256, -0.3885,  0.7327,  0.4326,
         1.0527,  0.4599,  1.5847, -0.1297, -0.3728,  1.0658,  0.3300,  1.2725,
         0.2430,  1.1166,  1.7991, -0.1855, -0.9254, -0.8039,  0.7636, -1.7128,
         0.9309, -0.0357, -0.8860,  0.6923, -0.5380,  0.7448, -0.0772, -1.1212,
        -0.3052, -0.6762, -1.1687, -0.25

In [32]:
tensor2

tensor([ 0.3922,  1.1391,  0.2841, -0.7790,  1.6449,  1.0221, -1.7182, -1.6343,
         0.2487, -0.4888, -2.8825, -1.7102, -1.2327, -0.3384, -0.8335, -0.5232,
         0.7534,  1.4202, -1.1226,  0.0666, -0.4747, -0.9797, -0.0944,  0.6974,
        -0.5711, -2.0456,  1.3225, -0.6843, -0.0503, -1.0659, -0.7152,  0.2676,
        -1.2623, -0.5159,  1.0853,  0.6972,  1.1244, -0.1457, -0.9527,  2.5243,
        -1.0070, -0.0808, -0.1834, -1.0681,  1.2177, -0.4248,  0.3191, -1.0837,
         0.8065, -0.0527, -2.1863,  1.4548, -0.7096, -0.3632, -0.5677,  0.8136,
         0.2832, -2.0763, -0.3234, -0.1697, -0.1939,  0.5540, -1.2226, -0.8015,
        -1.5055, -0.6939, -0.9862,  1.0086,  1.2559,  1.7641, -0.2702, -0.7329,
        -1.7332,  1.4386, -0.1102,  2.4374, -1.2242,  0.6411,  0.4677,  2.0771,
        -0.3598, -0.3826, -0.1926,  0.0975,  0.5471,  1.7082,  0.2831, -1.2768,
        -0.9681,  1.2656,  1.5260, -0.9530,  0.6672, -0.4590, -0.6602, -1.1045,
        -2.1879, -0.0332, -1.1798,  0.41

In [33]:
tensor2[0] = 0
tensor_div = tensor1/tensor2

In [34]:
tensor_min = tensor.min()
tensor_max = tensor.max()

In [35]:
tensor_sum = tensor1+ tensor2


In [36]:
tensor_max

tensor(1.0566)

In [37]:
tensor_min

tensor(-0.1288)

In [38]:
tensor_div

tensor([        inf,  6.9832e-01, -4.9765e+00, -1.8596e-01,  8.0323e-03,
         6.2069e-01, -6.4638e-02,  9.5777e-01,  1.2831e+00, -5.1515e-01,
         5.9401e-01, -5.0941e-01, -9.7750e-02,  2.5225e+00, -1.2763e+00,
        -1.2198e+00,  8.5828e-01, -2.3372e-01, -6.7191e-02, -2.6798e+01,
         1.2456e+00,  1.4427e+00,  8.7986e+00, -1.7331e+00,  1.0648e+00,
         1.4768e-01,  4.5351e-01, -7.6546e-01,  2.2201e+01, -4.0741e-01,
         5.9229e-01, -2.0384e+00,  1.8303e-01,  1.2976e+00,  1.9128e-01,
        -1.0082e+00, -2.7970e-01, -4.1398e-01,  1.5255e-01,  3.3832e-01,
         1.7643e+00, -4.8767e+00, -1.1241e+01, -1.0880e+00, -1.0435e+00,
         3.4357e+00,  2.0077e+00, -9.5552e-02,  1.0889e+00,  1.3207e+01,
         3.0568e-01, -7.1409e-01, -3.8254e-01, -3.7980e+00, -1.4860e+00,
         3.1494e-01,  1.4993e+00, -2.1098e-01,  6.6099e+00, -2.6900e-01,
        -1.4964e-01, -2.8149e+00, -5.8246e-01,  3.5009e+00, -5.4690e-01,
        -1.2949e+00,  5.8640e-01, -1.2670e+00, -5.7

In [39]:
tensor_diff = tensor1-tensor2

In [40]:
tensor_diff_sq = tensor_diff**2


tensor_diff_sq

tensor([1.5829e+00, 1.1809e-01, 2.8831e+00, 8.5352e-01, 2.6625e+00, 1.5029e-01,
        3.3464e+00, 4.7632e-03, 4.9577e-03, 5.4846e-01, 1.3696e+00, 6.6638e+00,
        1.8311e+00, 2.6539e-01, 3.5992e+00, 1.3489e+00, 1.1400e-02, 3.0701e+00,
        1.4352e+00, 3.4240e+00, 1.3585e-02, 1.8811e-01, 5.4160e-01, 3.6331e+00,
        1.3709e-03, 3.0399e+00, 5.2230e-01, 1.4596e+00, 1.1381e+00, 2.2505e+00,
        8.5020e-02, 6.6097e-01, 1.0635e+00, 2.3580e-02, 7.7032e-01, 1.9604e+00,
        2.0704e+00, 4.2449e-02, 6.5182e-01, 2.7899e+00, 5.9230e-01, 2.2535e-01,
        5.0376e+00, 4.9736e+00, 6.1917e+00, 1.0707e+00, 1.0338e-01, 1.4096e+00,
        5.1362e-03, 4.1419e-01, 2.3043e+00, 6.2185e+00, 9.6257e-01, 3.0369e+00,
        1.9920e+00, 3.1065e-01, 1.9994e-02, 6.3221e+00, 3.2925e+00, 4.6372e-02,
        4.9681e-02, 4.4672e+00, 3.7434e+00, 4.0176e+00, 5.4234e+00, 2.5360e+00,
        1.6636e-01, 5.2283e+00, 3.9264e+00, 4.6337e+00, 1.0059e+00, 1.3584e+00,
        7.7613e+00, 9.5793e-01, 2.8727e+

In [41]:
tensor_diff_sq.mean()

tensor(1.9595)

In [42]:
tensor_div.mean()

tensor(inf)

# Завдання 5

У вашому розпорядженні є нейронна мережа, яка прогнозує **орієнтовну ціну квартири** на основі двох **ознак**:

* **площі квартири** (у квадратних метрах);
* **кількості кімнат**.

Вам надано готовий клас `NeuralNetwork` із методом `predict`.

1. Створіть екземпляр класу `NeuralNetwork`, передайте як параметр `device`.
2. За допомогою методу `predict()` визначте прогнозовану ціну квартири, яка:
   * має площу **65 м²**;
   * має **2 кімнати**.
     
3. Для цього створіть тензор із відповідними числами та скористайтесь методом `predict()`.
4. Усі нейромережі очікують дані розміру `(N, K)`, де:
   * `N` — кількість об'єктів, для яких виконується прогноз;
   * `K` — кількість ознак. У цьому випадку їх дві — **площа квартири та кількість кімнат**.

5. Спробуйте скористатись методом `predict()` разом із `torch.no_grad()`:

```python
with torch.no_grad():
    price = model.predict(...)
```

**Завдання:** отримайте прогнозовану ціну квартири та виведіть результат на екран.


In [ ]:
import torch


class NeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [[3.3, -38.]],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [176.],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 2:
            raise ValueError(
                f"Очікується 2 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою (float32 або float64)."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        return X @ self.W.T + self.b


In [ ]:
# Ваш код


# **Завдання 6**

У таблиці наведено інформацію про три квартири.

| **Квартира** | **Площа (м²)** | **Кількість кімнат** |
| ------------ | -------------: | -------------------: |
| Квартира 1   |             40 |                    1 |
| Квартира 2   |             60 |                    3 |
| Квартира 3   |             100 |                    2 |

Виконайте наступні кроки:

1. Створіть **три окремі тензори** (`X1`, `X2`, `X3`), кожен з яких містить дані про одну квартиру.
2. За допомогою методу `predict()` обчисліть **прогнозовану ціну** для кожної квартири окремо.
3. Створіть **один тензор** `X` розміру **(3, 2)**, де:
   * кожен рядок відповідає одній квартирі;
   * перший стовпець — площа квартири;
   * другий стовпець — кількість кімнат.

4. За допомогою одного виклику `predict(X)` отримайте **прогнозовану ціну одразу для всіх трьох квартир**.
5. Виведіть розмір тензору з трьома прогнозованими цінами, який ви отримали на кроці 4.
6. Порівняйте результати, отримані окремими викликами `predict()` та одним спільним викликом `predict(X)`.


# Завдання 7

Три квартири були продані, і стали відомі їхні **реальні ціни**.

| Квартира   | Реальна ціна (1000$) |
| ---------- | ---------------: |
| Квартира 1 |           210 |
| Квартира 2 |          310 |
| Квартира 3 |          360 |

Нехай прогноз моделі збережений у змінній `y_pred`, а реальні значення — у `y_true`.

Визначте, **наскільки модель помилилася**, використавши два різних підходи.

### Варіант 1

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Обчисліть середнє значення цієї різниці за допомогою `torch.mean()`.

### Варіант 2

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Позбудьтеся від'ємних значень за допомогою `torch.abs()`.
3. Обчисліть середнє значення отриманих помилок.

### Запитання

1. Який із двох варіантів краще характеризує якість моделі? Поясніть свою відповідь.
2. Напишіть функцію `loss_fn()`, яка реалізує обраний варіант.

```python
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    ...
```




# Завдання 8

У вашому розпорядженні є вчитель, який може навчити нейронну мережу робити точніші прогнози **цін на квартири**.

Клас `Teacher` вже реалізований. Під час створення об'єкта необхідно передати модель, яку потрібно навчати:

```python
teacher = Teacher(model)
```

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Виведіть тензор `X`, який містить дані про квартири:
   * площу квартири;
   * кількість кімнат.

3. Виведіть тензор `y_true` з **реальними цінами квартир**.
4. Отримайте прогноз моделі `y_pred`.
5. Виведіть прогнозовані ціни квартир.
6. За допомогою власної функції `loss_fn()` обчисліть помилку моделі.
7. Виведіть значення помилки.
8. Скористайтеся методом `teach()` класу `Teacher`, передавши йому обчислену помилку.
9. Після навчання знову отримайте прогноз `y_pred`.
10. Виведіть нові прогнозовані ціни квартир.
11. Знову обчисліть та виведіть помилку.
12. Зробіть висновок: **чи стала модель прогнозувати ціни квартир точніше після одного кроку навчання?**



In [ ]:
import torch


class Teacher:
    def __init__(self, model, lr=0.02):
        """
        Створює вчителя для навчання моделі.

        Параметри:
            model (NeuralNetwork): модель, яку потрібно навчати.
            lr (float): швидкість навчання.
        """
        self.model = model

        self.optimizer = torch.optim.SGD(
            [model.W, model.b],
            lr=lr
        )

    def teach(self, loss):
        """
        Виконує один крок навчання.

        Параметри:
            loss (torch.Tensor): значення функції втрат.
        """
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()


# Завдання 9

Одного кроку навчання недостатньо, щоб модель навчилася добре прогнозувати ціни. Тому повторіть процес навчання **100 разів**.

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить дані про квартири.
3. Створіть тензор `y_true`, який містить реальні реальні ціни.
4. Створіть цикл, який виконається **100 разів**.
5. На кожній ітерації циклу:
   * отримайте прогноз моделі `y_pred`;
   * обчисліть помилку за допомогою функції `loss_fn()`;
   * виведіть помилку на екран;
   * передайте помилку в метод `teacher.teach()`, щоб виконати один крок навчання.
    
6. Після завершення циклу ще раз отримайте прогноз моделі.
7. Виведіть:
   * прогнозовані заробітні плати;
   * значення функції втрат.
    
8. Порівняйте отримані прогнози з реальними ціни. Зробіть висновок, чи покращилася точність моделі після 100 кроків навчання.
9. Cпробуйте зменшити навчальний крок в `teacher`

# Завдання 10

У вашому розпорядженні є нейронна мережа, яка прогнозує **ймовірність дощу**.

Модель використовує три ознаки:

* температура повітря (°C);
* вологість повітря (%);
* швидкість вітру (км/год).

Результатом роботи моделі є **два числа**:

1. ймовірність того, що **дощу не буде**;
2. ймовірність того, що **дощ буде**.

Скористайтеся методом `predict()`, щоб визначити ймовірності для таких погодних умов:

* температура — **20°C**;
* вологість — **80%**;
* швидкість вітру — **15 км/год**.



In [2]:
import torch


class RainNeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [
                [0.03, 0.01, 0.02],
                [0.06, -0.01, 0.08]
            ],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [-0.2, -0.3],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 3:
            raise ValueError(
                f"Очікується 3 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        logits = X @ self.W.T + self.b
        return torch.softmax(logits, dim=1)

# Завдання 11

Метеостанція надала прогноз погоди на **4 дні**.

| День | Температура (°C) | Вологість (%) | Швидкість вітру (км/год) |
| ---- | ---------------: | ------------: | -----------------------: |
| 1    |               30 |            40 |                        5 |
| 2    |               22 |            85 |                       18 |
| 3    |               15 |            95 |                       25 |
| 4    |               28 |            60 |                       10 |

Виконайте наступні кроки:

1. Створіть один тензор `X` розміру **(4, 3)**, де кожен рядок містить дані про один день.

2. За допомогою методу `predict()` отримайте ймовірності для кожного дня `y_pred`.

3. Скористайтеся функцією `torch.argmax(..., dim=1)`, щоб визначити прогноз моделі `result`:

   * `0` — дощу не буде;
   * `1` — дощ буде.

4. Виведіть:

   * тензор із ймовірностями `y_pred`;
   * тензор із прогнозами `result`


# Завдання 12

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
| ---- | :-: |
| 1    |  Ні |
| 2    | Так |
| 3    | Так |
| 4    |  Ні |

Для навчання моделі використайте готову функцію втрат **CrossEntropyLoss** з бібліотеки **PyTorch**.

### Завдання

1. Створіть об'єкт функції втрат:

   ```python
   loss_fn = torch.nn.CrossEntropyLoss()
   ```

2. Створіть об'єкт класу `Teacher`, передавши йому модель.

3. Створіть тензор `X`, який містить погодні умови за всі 4 дні.

4. Створіть тензор `y_true`, який містить правильні відповіді:

   * `0` — дощу не було;
   * `1` — дощ був.

5. Створіть цикл, який виконається **100 разів**.

6. На кожній ітерації циклу:

   * отримайте ймовірності від моделі `y_pred`:
   * обчисліть помилку:
   * виведіть помилку
   * передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

7. Після завершення циклу ще раз отримайте прогноз моделі.

8. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:

   * `0` — дощу не буде;
   * `1` — дощ буде.

9. Виведіть:

   * ймовірності, отримані від моделі;
   * прогнози моделі (`0` або `1`);
   * правильні відповіді
   * значення функції втра


# Завдання 13

Попробуйте натренувати модель використовуючи функцію втрат, яку ви раніше застосовували для задачі визначення цін на квартири (`torch.nn.MSELoss()`), замість `CrossEntropyLoss`.

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
|------|-----|
| 1    | Ні  |
| 2    | Так |
| 3    | Так |
| 4    | Ні  |

**Завдання**

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить погодні умови за всі 4 дні.
3. Створіть тензор `y_true` розміром (4, 2), де кожен рядок містить інформацію про те чи йшов дощ в цей день:
   - `[1, 0]` — дощу не було
   - `[0, 1]` — дощ був
   -  формат інший тому що ваша функція вимагає щоб `y_true` та `y_pred` були однакового розміру
4. Створіть цикл, який виконається 100 разів.

На кожній ітерації циклу:
- отримайте ймовірності від моделі `y_pred`;
- обчисліть помилку;
- виведіть помилку;
- передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

6. Після завершення циклу ще раз отримайте прогноз моделі.
7. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:
   - 0 — дощу не буде;
   - 1 — дощ буде.

**Виведіть:**
- ймовірності, отримані від моделі;
- прогнози моделі (0 або 1);
- правильні відповіді;
- значення функції втрат.
